name: feature-pipeline-daily
run-name: ${{ github.actor }} is gathering daily weather and air quality data
on:
    schedule:
        - cron: "0 8 * * *"
jobs:
  example-job:
      runs-on: ubuntu-latest
      steps:
          - name: Run build script
            run: ./.github/ID2223/project/feature-pipeline-daily.py
            shell: python
