name: feature-pipeline-daily
run-name: ${{ github.actor }} is gathering daily weather and air quality data
on:
    schedule:
        - cron: "0 8 * * *"
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: checkout repo content
            using: actions/checkout@v3
            
          - name: setup python
            uses: actions/setup-python@v4
            with:
              python-version: '3.9'
              
          - name: install python packages
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              
          - name: execute py script
            env:
              SOME_SECRET: ${{ secrets.HOPSWORKS_API_KEY }}
            run: python ./project/feature-pipeline-daily.py
