name: weekly-retraining-pipeline
run-name: ${{ github.actor }} is retraining the aqi prediction model with updated data
on:
    schedule:
        - cron: "0 12 * * 0"
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: checkout repo content
            uses: actions/checkout@v3
            
          - name: setup python
            uses: actions/setup-python@v4
            with:
              python-version: '3.8'
              
          - name: install python packages
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              
          - name: execute py script
            env:
              HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
            run: python ./project/training-pipeline.py
